name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # load nvm
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install 18
          nvm use 18

          # move into project
          cd /home/siteok/reviews-ok.online/www/reviews-ok

          # pull latest and install deps
          git pull origin main
          npm ci

          # <<< создаём/обновляем файл .env из GitHub Secrets
          cat > .env << 'EOF'
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          PORT=3000
          NODE_ENV=production
          EOF

          # restart via PM2 using ecosystem.config.js, dotenv будет читать .env
          pm2 delete reviews-ok || true
          pm2 start ecosystem.config.js --env production

