name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # 1. подготовка node
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install 18
          nvm use 18

          # 2. проект
          cd /home/siteok/reviews-ok.online/www/reviews-ok
          git pull origin main
          npm ci

          # 3. .env собираем из Secrets (ничего больше руками не правим!)
          cat > .env <<'EOF'
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          PORT=3000
          NODE_ENV=production
          EOF

          # 4. перезапуск через PM2
          pm2 delete reviews-ok || true
          pm2 start ecosystem.config.js --env production --update-env
